- hosts: localhost
  tasks:
        - name: Include credentials file(vault)
          include_vars: credentials.yml

        - name: Provison ec2 instances for Master Node
          ec2:
            image: "ami-098e42ae54c764c35"
            instance_type: "t3a.small"
            key_name: "rahul_sq"
            wait: yes
            count: 1
            state: present
            region: "us-west-2"
            vpc_subnet_id: "subnet-00614134196ed093d"
            group_id: "sg-062b0cbbc281cb60c"
            assign_public_ip: yes
            instance_tags:
              Name: Rahul_K8s_Master
            aws_access_key: "{{ user }}"
            aws_secret_key: "{{ paswd }}"


        - name: Updating the inventory or refreshing
          meta: refresh_inventory

        - name: Wait for instance to start
          ansible.builtin.pause:
            seconds: 20

- hosts: tag_Name_Rahul_K8s_Master
  gather_facts: no
  tasks:
        - name: Update Hostname
          hostname:
            name: "Master"
        - name: Install Docker
          package:
            name : docker
            state : present
        - name : Start Docker Service and enable permanently
          service :
            name : docker
            state : started
            enabled : yes
        - name : Add repo for kubernetes 
          copy :
            dest : "/etc/yum.repos.d/kubernetes.repo"
            src : conf/kubernetes.repo 
        - name : Install kubeadm, kubelet and kubectl
          shell :
            cmd : yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
        - name : Start Kubelet Service and enable permanently
          service :
            name : kubelet
            state : started
            enabled : yes
        - name : Pull images need for Kubernetes initialization
          shell :
            cmd : kubeadm config images pull
        - name : Change driver for Docker
          copy :
            dest : "/etc/docker/daemon.json"
            src : conf/daemon.json
        - name : Restart Docker Service
          service :
           name : docker
           state : restarted
        - name : Install iproute-tc 
          package : 
            name : iproute-tc
            state : present
        - name : Set IP Tables setting
          copy :
            src : conf/k8s.conf
            dest : /etc/sysctl.d/k8s.conf
        - name : Apply IP Table changes
          shell : 
            cmd : sysctl --system
        - name : Initialize Master Node 
          shell : 
            cmd : kubeadm init --pod-network-cidr=10.244.0.0/16
        - name : Capture Kubernetes Token from Master
          shell :
            cmd : kubeadm token create --print-join-command
          register : token
        - name : Save token in a file
          local_action: copy content={{ token.stdout }} dest=/token.txt

        - name : Configure Kubectl
          shell : "{{ item }}"
          with_items :
          - "mkdir -p $HOME/.kube"
          - "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
          - "chown $(id -u):$(id -g) $HOME/.kube/config"
        - name : Copy flannel file for CNI
          copy :
            src : conf/flannel.yml
            dest : /home/ec2-user/flannel.yml
        - name : Deploying flannel
          shell : 
            cmd : kubectl apply -f flannel.yml
